// Validierungs-Ergebnistypen + zentrale, stabile Fehlercodes.
// Reine Typen, kein any, keine Seiteneffekte.
import type { ProfessionContent } from "../../content/professions/types";

export type Severity = "error" | "warning";

// Zentral typisierte Codes (kein frei verteiltes String-Tippfehler-Risiko).
export type ValidationCode =
  // Identität
  | "PROFESSION_SLUG_EMPTY"
  | "PROFESSION_SLUG_INVALID"
  | "PROFESSION_NAME_EMPTY"
  | "PROFESSION_SHORTNAME_EMPTY"
  | "PROFESSION_PARENT_EMPTY"
  | "PROFESSION_CANONICAL_INVALID"
  | "PROFESSION_CANONICAL_MISMATCH"
  // Status / Veröffentlichung
  | "PROFESSION_PUBLISHED_FLAG_FALSE"
  | "PROFESSION_PUBLISHED_NOT_INDEXABLE"
  | "PROFESSION_PUBLISHED_NOT_IN_SITEMAP"
  | "PROFESSION_PUBLISHED_NOT_IN_HUB"
  | "PROFESSION_DRAFT_INDEXABLE"
  | "PROFESSION_DRAFT_IN_SITEMAP"
  | "PROFESSION_DRAFT_IN_HUB"
  // Metadata
  | "PROFESSION_METADATA_TITLE_EMPTY"
  | "PROFESSION_METADATA_DESCRIPTION_EMPTY"
  | "PROFESSION_METADATA_TITLE_TOO_LONG"
  | "PROFESSION_METADATA_DESCRIPTION_TOO_LONG"
  | "PROFESSION_PRIMARY_KEYWORD_EMPTY"
  | "PROFESSION_SECONDARY_KEYWORD_DUPLICATE"
  | "PROFESSION_SECONDARY_DUPLICATES_PRIMARY"
  | "PROFESSION_SEARCH_INTENT_INVALID"
  // Hero / CTA / Links
  | "PROFESSION_HERO_HEADLINE_EMPTY"
  | "PROFESSION_HERO_INTRO_EMPTY"
  | "PROFESSION_CTA_LABEL_EMPTY"
  | "PROFESSION_CTA_HREF_EMPTY"
  | "PROFESSION_CTA_INCOMPLETE"
  | "PROFESSION_LINK_INVALID"
  // Berufsinhalt
  | "PROFESSION_OVERVIEW_EMPTY"
  | "PROFESSION_TASKS_EMPTY"
  | "PROFESSION_INDUSTRIES_EMPTY"
  | "PROFESSION_REQUIREMENTS_EMPTY"
  | "PROFESSION_FAQ_EMPTY"
  | "PROFESSION_FAQ_QUESTION_EMPTY"
  | "PROFESSION_FAQ_ANSWER_EMPTY"
  | "PROFESSION_FAQ_DUPLICATE_QUESTION"
  | "PROFESSION_SPECIALIZATION_DUPLICATE_TITLE"
  | "PROFESSION_INDUSTRY_DUPLICATE_NAME"
  | "PROFESSION_CONTENT_THIN"
  // Job-Matching
  | "PROFESSION_JOB_MATCH_MAXJOBS_INVALID"
  | "PROFESSION_JOB_MATCH_EMPTY"
  | "PROFESSION_JOB_MATCH_INCLUDE_EXCLUDE_OVERLAP"
  | "PROFESSION_JOB_MATCH_TAG_EMPTY"
  | "PROFESSION_JOB_MATCH_KEYWORD_EMPTY"
  | "PROFESSION_JOB_MATCH_TAG_DUPLICATE"
  | "PROFESSION_JOB_MATCH_KEYWORD_DUPLICATE"
  | "PROFESSION_JOB_MATCH_CATEGORY_INVALID"
  | "PROFESSION_JOB_MATCH_FALLBACK_INVALID"
  | "PROFESSION_JOB_MATCH_KEYWORDS_ONLY"
  | "PROFESSION_JOB_MATCH_TOO_BROAD"
  | "PROFESSION_JOB_MATCH_NO_EXCLUDE"
  // Interne Links
  | "PROFESSION_INTERNAL_PARENT_MISSING"
  | "PROFESSION_INTERNAL_JOBS_MISSING"
  | "PROFESSION_INTERNAL_LEBENSLAUF_MISSING"
  | "PROFESSION_INTERNAL_PERSONALVERMITTLUNG_MISSING"
  | "PROFESSION_INTERNAL_KONTAKT_MISSING"
  | "PROFESSION_INTERNAL_LINK_INVALID"
  | "PROFESSION_RELATED_SELF_REFERENCE"
  | "PROFESSION_RELATED_DUPLICATE"
  // Verbotene Inhalte
  | "PROFESSION_FORBIDDEN_CLAIM"
  // Registry
  | "REGISTRY_DUPLICATE_SLUG"
  | "REGISTRY_DUPLICATE_CANONICAL"
  | "REGISTRY_DUPLICATE_TITLE"
  | "REGISTRY_DUPLICATE_PRIMARY_KEYWORD"
  | "REGISTRY_PUBLISHED_ARRAY_MISMATCH"
  | "REGISTRY_DRAFT_ARRAY_MISMATCH"
  | "REGISTRY_PROFESSION_MISSING_IN_SUBARRAYS"
  | "REGISTRY_PROFESSION_IN_BOTH_SUBARRAYS"
  | "REGISTRY_BYSLUG_MISSING"
  | "REGISTRY_BYSLUG_MISMATCH"
  | "REGISTRY_RELATED_NOT_FOUND"
  | "REGISTRY_RELATED_NOT_PUBLISHED"
  | "REGISTRY_DRAFT_RELATED_DRAFT"
  | "REGISTRY_PUBLISHED_HAS_ERRORS";

export type ValidationIssue = {
  readonly code: ValidationCode;
  readonly message: string;
  readonly path: string; // z. B. "hero.primaryCta.href"
  readonly severity: Severity;
  readonly professionSlug?: string;
};

export type ValidationResult = {
  readonly valid: boolean; // true, wenn keine errors
  readonly errors: readonly ValidationIssue[];
  readonly warnings: readonly ValidationIssue[];
};

// Eingabeform für die Registry-Validierung (statische Strukturen aus 006B).
export type ProfessionRegistryInput = {
  readonly professions: readonly ProfessionContent[];
  readonly publishedProfessions: readonly ProfessionContent[];
  readonly draftProfessions: readonly ProfessionContent[];
  readonly professionBySlug: Readonly<Record<string, ProfessionContent>>;
};
