export type Job = {
  id: string;
  title: string;
  category: "elektro" | "mechatronik" | "it" | "bau";
  city: string;
  region: string;
  lat: number;
  lng: number;
  salary: string;
  type: string;
  tags: string[];
  description: string;
  posted: string;
  benefits: string[];
  datePosted: string; // ISO-Datum der Veröffentlichung — Quelle für JobPosting-Schema
  intro?: string; // einzigartige Einleitung zur Stelle (2-3 Sätze)
  aufgaben?: string[]; // rollentypische Aufgaben-Bullets
  profil?: string[]; // Anforderungsprofil-Bullets
};

// Gültigkeitsdauer einer Ausschreibung für das JobPosting-Schema
export function validThroughOf(job: Job): string {
  const d = new Date(job.datePosted);
  d.setDate(d.getDate() + 90);
  return d.toISOString().split("T")[0];
}

// "45.000 – 50.000 €/Jahr" → { min: 45000, max: 50000 }
export function parseSalaryRange(salary: string): { min: number; max: number } | null {
  const nums = salary.match(/\d{1,3}(?:\.\d{3})+/g);
  if (!nums?.length) return null;
  const vals = nums.map(n => parseInt(n.replace(/\./g, ""), 10)).filter(v => v >= 10000);
  if (!vals.length) return null;
  return { min: Math.min(...vals), max: Math.max(...vals) };
}

export const JOBS: Job[] = [
  {
    id: "1",
    title: "Elektroniker für Betriebstechnik (m/w/d)",
    category: "elektro",
    city: "Frankenthal",
    region: "Rheinland-Pfalz",
    lat: 49.537,
    lng: 8.353,
    salary: "45.000 – 50.000 €/Jahr",
    type: "Festanstellung",
    datePosted: "2026-06-26",
    tags: ["Schaltschrankbau", "Instandhaltung", "Gleitzeit"],
    description: "Verdrahtung von Schaltschränken, Montage und elektrische Installation von Maschinen und Anlagen. Keine Schichtarbeit, saubere Produktionsumgebung.",
    intro: "Für einen Produktionsstandort in Frankenthal (Rheinland-Pfalz) suchen wir einen Elektroniker für Betriebstechnik. Sie arbeiten in einer sauberen Produktionsumgebung mit Gleitzeit und ohne Schichtarbeit – der Schwerpunkt liegt auf dem Schaltschrankbau und der elektrischen Installation von Maschinen und Anlagen.",
    aufgaben: [
      "Verdrahtung und Aufbau von Schaltschränken nach Stromlaufplan",
      "Montage und elektrische Installation von Maschinen und Anlagen",
      "Durchführung von Funktionsprüfungen und Inbetriebnahmen",
      "Instandhaltung und Störungsbeseitigung an elektrischen Betriebsmitteln",
      "Prüfungen elektrischer Anlagen nach DIN VDE 0100-600 und DGUV Vorschrift 3",
      "Dokumentation der durchgeführten Arbeiten und Pflege der Schaltpläne",
    ],
    profil: [
      "Abgeschlossene Ausbildung als Elektroniker für Betriebstechnik, Elektroniker für Energie- und Gebäudetechnik oder vergleichbar",
      "Erfahrung im Schaltschrankbau oder in der industriellen Instandhaltung von Vorteil",
      "Sicheres Lesen von Stromlaufplänen und technischen Zeichnungen",
      "Gute Deutschkenntnisse in Wort und Schrift",
      "Sorgfältige und selbstständige Arbeitsweise",
    ],
    posted: "vor 2 Tagen",
    benefits: ["30 Tage Urlaub", "Gleitzeit", "Betriebliche Altersvorsorge", "Weiterbildungsbudget"],
  },
  {
    id: "2",
    title: "Servicetechniker Kältetechnik (m/w/d)",
    category: "mechatronik",
    city: "München",
    region: "Bayern",
    lat: 48.137,
    lng: 11.576,
    salary: "50.000 – 65.000 €/Jahr",
    type: "Festanstellung",
    datePosted: "2026-06-26",
    tags: ["Kältetechnik", "Tiefkühlung", "Wartung"],
    description: "Wartung, Instandhaltung und Reparatur von Tiefkälteanlagen (bis –80 °C). Fehlerdiagnose und Austausch defekter Komponenten im Kundendienst.",
    intro: "Im Großraum München betreuen Sie als Servicetechniker Tiefkälteanlagen mit Temperaturen bis –80 °C – ein anspruchsvolles Spezialgebiet der Kältetechnik. Die Einsätze erfolgen im Kundendienst, ein Firmenwagen mit privater Nutzung gehört zur Ausstattung.",
    aufgaben: [
      "Wartung, Instandhaltung und Reparatur von Tiefkälteanlagen bis –80 °C",
      "Systematische Fehlerdiagnose an Kältekreisläufen, Verdichtern und Regelungstechnik",
      "Dichtheitsprüfungen und Dokumentation gemäß ChemKlimaschutzV und F-Gase-Verordnung",
      "Fachgerechtes Kältemittel-Handling inklusive Rückgewinnung und Befüllung",
      "Austausch defekter Komponenten mit anschließender Funktionsprüfung",
      "Erstellung von Serviceberichten und Abstimmung mit den Ansprechpartnern vor Ort",
    ],
    profil: [
      "Abgeschlossene Ausbildung als Mechatroniker für Kältetechnik oder vergleichbare Qualifikation",
      "Sachkundebescheinigung Kategorie I nach ChemKlimaschutzV von Vorteil",
      "Erfahrung im Kundendienst oder in der Tiefkühltechnik wünschenswert",
      "Führerschein Klasse B für den Einsatz im Servicegebiet",
      "Gute Deutschkenntnisse und sicheres Auftreten beim Kunden",
    ],
    posted: "vor 3 Tagen",
    benefits: ["Firmenwagen (auch privat)", "30 Tage Urlaub", "Spesen & Auslöse", "Betriebliche Altersvorsorge"],
  },
  {
    id: "3",
    title: "Servicetechniker Elektrotechnik (m/w/d)",
    category: "elektro",
    city: "Leipzig",
    region: "Sachsen",
    lat: 51.340,
    lng: 12.375,
    salary: "46.000 – 52.000 €/Jahr",
    type: "Festanstellung",
    datePosted: "2026-06-26",
    tags: ["Wartung", "Instandhaltung", "Außendienst"],
    description: "Wartung, Prüfung und Instandhaltung elektrischer Systeme und Anlagen beim Kunden vor Ort. Mo–Fr, keine Wochenendarbeit.",
    intro: "Für Kundeneinsätze im Raum Leipzig suchen wir einen Servicetechniker Elektrotechnik. Die Einsätze finden von Montag bis Freitag statt – Wochenendarbeit ist nicht vorgesehen, für den Außendienst steht ein Firmenwagen bereit.",
    aufgaben: [
      "Wartung und Instandhaltung elektrischer Systeme und Anlagen beim Kunden vor Ort",
      "Prüfungen ortsfester Anlagen nach DGUV Vorschrift 3 und DIN VDE 0105-100",
      "Fehlersuche und Störungsbeseitigung an elektrotechnischen Einrichtungen",
      "Austausch und Nachrüstung elektrischer Komponenten",
      "Dokumentation der Prüf- und Wartungsergebnisse",
      "Abstimmung der Einsätze mit der Disposition und den Ansprechpartnern vor Ort",
    ],
    profil: [
      "Abgeschlossene Ausbildung als Elektroniker, Elektroinstallateur oder vergleichbar",
      "Erfahrung im Außendienst oder in der Anlagenprüfung von Vorteil",
      "Führerschein Klasse B",
      "Gute Deutschkenntnisse für die Kommunikation mit Kunden",
      "Selbstständige und zuverlässige Arbeitsweise",
    ],
    posted: "vor 1 Woche",
    benefits: ["Keine Wochenendarbeit", "Firmenwagen", "30 Tage Urlaub", "Betriebliche Altersvorsorge"],
  },
  {
    id: "4",
    title: "Elektromonteur (m/w/d)",
    category: "elektro",
    city: "Offenbach",
    region: "Hessen",
    lat: 50.099,
    lng: 8.762,
    salary: "42.000 – 46.000 €/Jahr",
    type: "Festanstellung",
    datePosted: "2026-06-26",
    tags: ["Montage", "Elektroinstallation", "Inbetriebnahme"],
    description: "Installation und Montage von elektrotechnischen Anlagen beim Kunden vor Ort. Verkabelung, Anschlussarbeiten und Inbetriebnahme.",
    intro: "Als Elektromonteur in Offenbach installieren und montieren Sie elektrotechnische Anlagen direkt beim Kunden. Die Position bietet abwechslungsreiche Einsatzorte im Rhein-Main-Gebiet und geregelte Abläufe mit Überstundenausgleich.",
    aufgaben: [
      "Installation und Montage elektrotechnischer Anlagen beim Kunden vor Ort",
      "Verlegen von Kabeltrassen und Leitungen sowie Anschlussarbeiten",
      "Aufbau und Anschluss von Verteilungen und Unterverteilungen",
      "Mitwirkung bei Inbetriebnahmen und Funktionsprüfungen nach DIN VDE 0100",
      "Fehlersuche und Nacharbeiten im Rahmen der Montageeinsätze",
      "Dokumentation der ausgeführten Installationsarbeiten",
    ],
    profil: [
      "Abgeschlossene Ausbildung als Elektroniker für Energie- und Gebäudetechnik, Elektromonteur oder vergleichbar",
      "Erfahrung in der Elektroinstallation auf Baustellen von Vorteil",
      "Führerschein Klasse B wünschenswert",
      "Gute Deutschkenntnisse in Wort und Schrift",
      "Teamfähigkeit und eine sorgfältige Arbeitsweise",
    ],
    posted: "vor 4 Tagen",
    benefits: ["Überstundenausgleich", "Weiterbildungsbudget", "Jobticket", "Betriebliche Altersvorsorge"],
  },
  {
    id: "5",
    title: "Elektroniker Instandhaltung (m/w/d)",
    category: "elektro",
    city: "Mosbach",
    region: "Baden-Württemberg",
    lat: 49.353,
    lng: 9.149,
    salary: "46.000 – 50.000 €/Jahr",
    type: "Festanstellung",
    datePosted: "2026-06-26",
    tags: ["Instandhaltung", "Produktion", "Keine Schicht"],
    description: "Instandhaltung und Reparatur elektrischer Anlagen in einem Produktionsunternehmen. Feste Arbeitszeiten, keine Schichtarbeit.",
    intro: "In einem Produktionsunternehmen in Mosbach (Baden-Württemberg) kümmern Sie sich um die elektrische Instandhaltung – zu festen Arbeitszeiten und ohne Schichtarbeit. Die Stelle eignet sich für Elektroniker, die planbare Tage und einen festen Standort schätzen.",
    aufgaben: [
      "Instandhaltung und Reparatur elektrischer Anlagen in der Produktion",
      "Analyse und Behebung von Störungen an Maschinen und Betriebsmitteln",
      "Durchführung vorbeugender Wartungsmaßnahmen nach Wartungsplan",
      "Prüfung ortsveränderlicher und ortsfester Betriebsmittel nach DGUV Vorschrift 3",
      "Unterstützung bei Umbauten und Erweiterungen der Anlagentechnik",
      "Pflege der Instandhaltungsdokumentation",
    ],
    profil: [
      "Abgeschlossene Ausbildung als Elektroniker, Elektriker oder in einem vergleichbaren Elektroberuf",
      "Erfahrung in der Instandhaltung von Produktionsanlagen von Vorteil",
      "Kenntnisse im Lesen von Schalt- und Stromlaufplänen",
      "Gute Deutschkenntnisse",
      "Strukturierte und eigenverantwortliche Arbeitsweise",
    ],
    posted: "vor 5 Tagen",
    benefits: ["Keine Schichtarbeit", "30 Tage Urlaub", "Betriebliche Altersvorsorge", "Mitarbeiterrabatte"],
  },
  {
    id: "6",
    title: "Betriebselektriker (m/w/d)",
    category: "elektro",
    city: "Münster",
    region: "Nordrhein-Westfalen",
    lat: 51.960,
    lng: 7.626,
    salary: "42.000 – 50.000 €/Jahr",
    type: "Festanstellung",
    datePosted: "2026-06-26",
    tags: ["Betriebstechnik", "Wartung", "Produktion"],
    description: "Sicherstellung der elektrischen Betriebsbereitschaft von Maschinen und Anlagen. Störungsbeseitigung und vorbeugende Wartung.",
    intro: "Als Betriebselektriker in Münster sorgen Sie dafür, dass Maschinen und Anlagen elektrisch zuverlässig laufen. Der Fokus liegt auf schneller Störungsbeseitigung und vorbeugender Wartung in einem produzierenden Umfeld.",
    aufgaben: [
      "Sicherstellung der elektrischen Betriebsbereitschaft von Maschinen und Anlagen",
      "Schnelle Analyse und Beseitigung elektrischer Störungen im laufenden Betrieb",
      "Planung und Durchführung vorbeugender Wartungsmaßnahmen",
      "Wiederkehrende Prüfungen nach DGUV Vorschrift 3",
      "Zusammenarbeit mit Produktion und mechanischer Instandhaltung",
      "Dokumentation von Störungen und abgeleiteten Verbesserungsmaßnahmen",
    ],
    profil: [
      "Abgeschlossene Ausbildung als Elektriker, Elektroniker für Betriebstechnik oder vergleichbar",
      "Berufserfahrung als Betriebselektriker von Vorteil",
      "Kenntnisse in Steuerungstechnik wünschenswert",
      "Gute Deutschkenntnisse in Wort und Schrift",
      "Zuverlässige, lösungsorientierte Arbeitsweise",
    ],
    posted: "vor 6 Tagen",
    benefits: ["30 Tage Urlaub", "Weiterbildungsbudget", "Betriebliche Altersvorsorge", "Kantine"],
  },
  {
    id: "7",
    title: "SPS-Programmierer / Automatisierungstechniker (m/w/d)",
    category: "it",
    city: "Langenfeld",
    region: "Nordrhein-Westfalen",
    lat: 51.107,
    lng: 6.949,
    salary: "50.000 – 65.000 €/Jahr",
    type: "Festanstellung",
    datePosted: "2026-06-26",
    tags: ["Siemens TIA Portal", "SPS", "Automatisierung"],
    description: "Entwicklung und Optimierung von SPS-Programmen für Produktionsanlagen. Inbetriebnahme und Optimierung von Automatisierungslösungen.",
    intro: "Für einen Standort in Langenfeld zwischen Köln und Düsseldorf suchen wir einen SPS-Programmierer bzw. Automatisierungstechniker. Sie entwickeln Steuerungslösungen mit dem Siemens TIA Portal und können anteilig im Homeoffice arbeiten.",
    aufgaben: [
      "Entwicklung und Optimierung von SPS-Programmen mit Siemens TIA Portal (S7-1200/1500)",
      "Inbetriebnahme von Automatisierungslösungen an Produktionsanlagen",
      "Störungsanalyse und Fehlerbehebung in der Steuerungs- und Antriebstechnik",
      "Prozessoptimierung in Zusammenarbeit mit Produktion und Instandhaltung",
      "Erstellung und Anpassung von Visualisierungen (HMI/WinCC)",
      "Dokumentation der Softwarestände und Programmänderungen",
    ],
    profil: [
      "Abgeschlossene Ausbildung als Elektroniker für Automatisierungstechnik, staatlich geprüfter Techniker oder vergleichbar",
      "Erfahrung in der SPS-Programmierung mit TIA Portal oder Step 7",
      "Kenntnisse in Bussystemen wie Profinet oder Profibus von Vorteil",
      "Gute Deutschkenntnisse für Dokumentation und Abstimmung",
      "Analytische und strukturierte Arbeitsweise",
    ],
    posted: "vor 3 Tagen",
    benefits: ["Homeoffice möglich", "30 Tage Urlaub", "Weiterbildungsbudget", "Betriebliche Altersvorsorge"],
  },
  {
    id: "8",
    title: "Betriebselektroniker (m/w/d)",
    category: "elektro",
    city: "Bad Oeynhausen",
    region: "Nordrhein-Westfalen",
    lat: 52.198,
    lng: 8.800,
    salary: "44.000 – 52.000 €/Jahr",
    type: "Festanstellung",
    datePosted: "2026-06-26",
    tags: ["Elektronik", "Instandhaltung", "Produktion"],
    description: "Wartung und Instandhaltung elektronischer Betriebsmittel. Fehlerdiagnose und Reparatur an Produktionsanlagen.",
    intro: "Am Standort Bad Oeynhausen in Ostwestfalen halten Sie als Betriebselektroniker die elektronischen Betriebsmittel der Produktion instand. Der Schwerpunkt liegt auf Fehlerdiagnose und Reparatur direkt an den Produktionsanlagen.",
    aufgaben: [
      "Wartung und Instandhaltung elektronischer Betriebsmittel in der Produktion",
      "Fehlerdiagnose an Produktionsanlagen mit moderner Mess- und Prüftechnik",
      "Reparatur und Austausch elektronischer Baugruppen und Sensorik",
      "Begleitung von Anlagenstillständen und geplanten Wartungsfenstern",
      "Durchführung von Prüfungen nach DGUV Vorschrift 3",
      "Dokumentation der Instandhaltungsmaßnahmen",
    ],
    profil: [
      "Abgeschlossene Ausbildung als Elektroniker für Betriebstechnik, für Geräte und Systeme oder vergleichbar",
      "Erfahrung in der Instandhaltung von Produktionsanlagen von Vorteil",
      "Bereitschaft zur Arbeit im Schichtsystem",
      "Gute Deutschkenntnisse",
      "Sorgfältige und teamorientierte Arbeitsweise",
    ],
    posted: "vor 1 Woche",
    benefits: ["30 Tage Urlaub", "Schichtzulage", "Betriebliche Altersvorsorge", "Mitarbeiterrabatte"],
  },
  {
    id: "9",
    title: "Betriebselektroniker (m/w/d)",
    category: "elektro",
    city: "Kerpen",
    region: "Nordrhein-Westfalen",
    lat: 50.869,
    lng: 6.695,
    salary: "42.000 – 52.000 €/Jahr",
    type: "Festanstellung",
    datePosted: "2026-06-26",
    tags: ["Elektronik", "Betriebstechnik", "NRW"],
    description: "Instandhaltung und Reparatur elektronischer Anlagen in einem wachsenden Produktionsunternehmen. Abwechslungsreiche Aufgaben.",
    intro: "In Kerpen westlich von Köln erwartet Sie eine Position als Betriebselektroniker in einem wachsenden Produktionsunternehmen. Die Aufgaben sind bewusst breit angelegt – von der Störungsbehebung bis zur Mitarbeit an neuen Anlagen.",
    aufgaben: [
      "Instandhaltung und Reparatur elektronischer Anlagen und Systeme",
      "Eigenständige Eingrenzung und Behebung von Störungen",
      "Mitwirkung bei Installation und Inbetriebnahme neuer Produktionstechnik",
      "Optimierung bestehender Anlagen gemeinsam mit der Instandhaltung",
      "Wiederkehrende Prüfungen elektrischer Betriebsmittel nach DGUV Vorschrift 3",
      "Führen der technischen Dokumentation",
    ],
    profil: [
      "Abgeschlossene Ausbildung in einem elektrotechnischen Beruf, z. B. als Elektroniker für Betriebstechnik",
      "Erfahrung in der Betriebstechnik oder Instandhaltung von Vorteil",
      "Interesse an abwechslungsreichen Aufgaben in einem wachsenden Umfeld",
      "Gute Deutschkenntnisse in Wort und Schrift",
      "Hands-on-Mentalität und selbstständige Arbeitsweise",
    ],
    posted: "vor 2 Wochen",
    benefits: ["30 Tage Urlaub", "Betriebliche Altersvorsorge", "Jobrad", "Mitarbeiterevents"],
  },
  {
    id: "10",
    title: "Mechatroniker (m/w/d)",
    category: "mechatronik",
    city: "Freiburg",
    region: "Baden-Württemberg",
    lat: 47.997,
    lng: 7.842,
    salary: "45.000 – 55.000 €/Jahr",
    type: "Festanstellung",
    datePosted: "2026-06-26",
    tags: ["Mechatronik", "Montage", "Inbetriebnahme"],
    description: "Montage, Inbetriebnahme und Wartung mechatronischer Systeme. Abwechslungsreiche Tätigkeit in einem modernen Unternehmen.",
    intro: "Als Mechatroniker in Freiburg verbinden Sie Mechanik, Elektronik und Steuerungstechnik in einer Rolle. Sie montieren mechatronische Systeme, nehmen sie in Betrieb und halten sie instand – mit moderner Werkzeugausstattung.",
    aufgaben: [
      "Montage mechatronischer Systeme und Baugruppen nach Zeichnung",
      "Inbetriebnahme und Einstellung von Maschinen und Anlagen",
      "Wartung und Instandhaltung mechanischer, elektrischer und pneumatischer Komponenten",
      "Fehlersuche an den Schnittstellen von Mechanik, Elektrik und Steuerung",
      "Durchführung von Funktions- und Sicherheitsprüfungen",
      "Dokumentation der Montage- und Serviceeinsätze",
    ],
    profil: [
      "Abgeschlossene Ausbildung als Mechatroniker oder vergleichbare Qualifikation",
      "Erfahrung in Montage oder Instandhaltung von Vorteil",
      "Kenntnisse in Pneumatik und Steuerungstechnik wünschenswert",
      "Gute Deutschkenntnisse",
      "Sorgfältige, qualitätsbewusste Arbeitsweise",
    ],
    posted: "vor 3 Tagen",
    benefits: ["30 Tage Urlaub", "Weiterbildungsbudget", "Betriebliche Altersvorsorge", "Moderne Werkzeuge"],
  },
  {
    id: "11",
    title: "Elektroniker für Betriebstechnik – Vollkonti (m/w/d)",
    category: "elektro",
    city: "Erding",
    region: "Bayern",
    lat: 48.306,
    lng: 11.907,
    salary: "50.000 – 60.000 €/Jahr",
    type: "Festanstellung",
    datePosted: "2026-06-26",
    tags: ["Vollkontinuierlich", "Schichtarbeit", "Produktion"],
    description: "Instandhaltung elektrischer Anlagen im Vollkontinuierlichen Schichtbetrieb. Attraktive Schichtzulagen, 30 Urlaubstage.",
    intro: "Für einen Produktionsstandort in Erding bei München suchen wir einen Elektroniker für Betriebstechnik im vollkontinuierlichen Schichtbetrieb. Die Anlagentechnik läuft rund um die Uhr – die Vollkonti-Schicht wird entsprechend mit Zulagen vergütet.",
    aufgaben: [
      "Elektrische Instandhaltung der Produktionsanlagen im Vollkonti-Betrieb",
      "Störungssuche und -behebung während der laufenden Schicht",
      "Vorbeugende Wartung nach Instandhaltungsplan",
      "Enge Zusammenarbeit mit dem Schichtteam der Produktion",
      "Prüfungen elektrischer Anlagen und Betriebsmittel nach DGUV Vorschrift 3",
      "Schichtübergabe und Dokumentation im Schichtbuch",
    ],
    profil: [
      "Abgeschlossene Ausbildung als Elektroniker für Betriebstechnik oder vergleichbar",
      "Bereitschaft zum vollkontinuierlichen Schichtsystem inklusive Wochenenden",
      "Erfahrung in der industriellen Instandhaltung von Vorteil",
      "Gute Deutschkenntnisse",
      "Belastbarkeit und zuverlässige Arbeitsweise",
    ],
    posted: "vor 5 Tagen",
    benefits: ["30 Tage Urlaub", "Schichtzulage", "Betriebliche Altersvorsorge", "Kantine"],
  },
  {
    id: "12",
    title: "Elektroniker für Betriebstechnik – 3-Schicht (m/w/d)",
    category: "elektro",
    city: "Heilbronn",
    region: "Baden-Württemberg",
    lat: 49.142,
    lng: 9.220,
    salary: "46.000 – 54.000 €/Jahr",
    type: "Festanstellung",
    datePosted: "2026-06-26",
    tags: ["3-Schicht", "Instandhaltung", "Automatisierung"],
    description: "Elektrische Instandhaltung von Maschinen und Anlagen im 3-Schicht-Betrieb. Keine Wochenendarbeit, attraktive Schichtzulage.",
    intro: "Am Standort Heilbronn übernehmen Sie die elektrische Instandhaltung automatisierter Maschinen und Anlagen im 3-Schicht-System – Wochenendarbeit ist nicht vorgesehen. Die Schichten werden zusätzlich vergütet.",
    aufgaben: [
      "Elektrische Instandhaltung von Maschinen und Anlagen im 3-Schicht-Betrieb",
      "Fehlerdiagnose an automatisierten Anlagen inklusive Sensorik und Antriebstechnik",
      "Behebung von Störungen an SPS-gesteuerten Produktionslinien",
      "Durchführung geplanter Wartungs- und Inspektionsarbeiten",
      "Mitwirkung bei der Verbesserung der Anlagenverfügbarkeit",
      "Dokumentation der Einsätze in der Instandhaltungssoftware",
    ],
    profil: [
      "Abgeschlossene Ausbildung als Elektroniker für Betriebstechnik oder Automatisierungstechnik",
      "Erfahrung mit SPS-gesteuerten Anlagen von Vorteil",
      "Bereitschaft zur Arbeit im 3-Schicht-System von Montag bis Freitag",
      "Gute Deutschkenntnisse",
      "Teamfähigkeit und strukturierte Arbeitsweise",
    ],
    posted: "vor 1 Woche",
    benefits: ["Keine Wochenendarbeit", "Schichtzulage", "30 Tage Urlaub", "Betriebliche Altersvorsorge"],
  },
  {
    id: "13",
    title: "Elektroniker MSR-Technik / Gebäudeautomation (m/w/d)",
    category: "elektro",
    city: "Köln",
    region: "Nordrhein-Westfalen",
    lat: 50.938,
    lng: 6.960,
    salary: "48.000 – 58.000 €/Jahr",
    type: "Festanstellung",
    datePosted: "2026-06-26",
    tags: ["MSR-Technik", "Gebäudeautomation", "HLK"],
    description: "Planung, Installation und Inbetriebnahme von MSR-Technik in HLK-Anlagen. Service und Wartung von Gebäudeautomationssystemen.",
    intro: "Für Projekte im Raum Köln suchen wir einen Elektroniker für MSR-Technik und Gebäudeautomation. Sie bringen HLK-Anlagen regelungstechnisch zum Laufen – von der Installation bis zur Inbetriebnahme – und sind mit dem Firmenwagen zwischen den Objekten unterwegs.",
    aufgaben: [
      "Installation und Verdrahtung von MSR-Technik in HLK-Anlagen",
      "Inbetriebnahme und Parametrierung von DDC-Unterstationen und GLT-Systemen",
      "Aufschaltung von Feldgeräten wie Fühlern, Ventilen und Klappenantrieben",
      "Service und Wartung bestehender Gebäudeautomationssysteme",
      "Fehlersuche in Regelkreisen und Optimierung der Anlagenparameter",
      "Einweisung von Betreibern und Erstellung der Anlagendokumentation",
    ],
    profil: [
      "Abgeschlossene Ausbildung als Elektroniker, idealerweise mit Bezug zur Gebäude- oder Automatisierungstechnik",
      "Erfahrung mit DDC/GLT-Systemen oder MSR-Technik von Vorteil",
      "Führerschein Klasse B für Einsätze im Servicegebiet",
      "Gute Deutschkenntnisse für den Kontakt mit Kunden und Betreibern",
      "Selbstständige und dienstleistungsorientierte Arbeitsweise",
    ],
    posted: "vor 4 Tagen",
    benefits: ["Firmenwagen", "30 Tage Urlaub", "Weiterbildungsbudget", "Betriebliche Altersvorsorge"],
  },
  {
    id: "14",
    title: "Mechatroniker als Servicetechniker (m/w/d)",
    category: "mechatronik",
    city: "Bremen",
    region: "Bremen",
    lat: 53.079,
    lng: 8.801,
    salary: "44.000 – 54.000 €/Jahr",
    type: "Festanstellung",
    datePosted: "2026-06-26",
    tags: ["Service", "Außendienst", "Mechatronik"],
    description: "Wartung und Instandhaltung mechatronischer Anlagen beim Kunden. Serviceorientierter Einsatz im Raum Bremen.",
    intro: "Im Raum Bremen betreuen Sie als Servicetechniker mechatronische Anlagen direkt bei Kunden vor Ort. Die Einsätze bleiben im regionalen Umfeld – ein Firmenwagen mit privater Nutzung steht Ihnen dafür zur Verfügung.",
    aufgaben: [
      "Wartung und Instandhaltung mechatronischer Anlagen bei Kunden im Raum Bremen",
      "Fehlersuche an mechanischen, elektrischen und steuerungstechnischen Komponenten",
      "Reparatur und Austausch von Verschleißteilen und Baugruppen",
      "Funktionsprüfungen nach abgeschlossenen Serviceeinsätzen",
      "Beratung der Kunden zu Wartungsintervallen und Anlagenzustand",
      "Erstellung aussagekräftiger Serviceberichte",
    ],
    profil: [
      "Abgeschlossene Ausbildung als Mechatroniker oder vergleichbar",
      "Erfahrung im technischen Kundendienst von Vorteil",
      "Führerschein Klasse B",
      "Gute Deutschkenntnisse und freundliches Auftreten beim Kunden",
      "Eigenverantwortliche und flexible Arbeitsweise",
    ],
    posted: "vor 2 Tagen",
    benefits: ["Firmenwagen (auch privat)", "Spesen & Auslöse", "30 Tage Urlaub", "Betriebliche Altersvorsorge"],
  },
  {
    id: "15",
    title: "Kältetechniker (m/w/d)",
    category: "mechatronik",
    city: "Koblenz",
    region: "Rheinland-Pfalz",
    lat: 50.359,
    lng: 7.590,
    salary: "46.000 – 56.000 €/Jahr",
    type: "Festanstellung",
    datePosted: "2026-06-26",
    tags: ["Kältetechnik", "HKLS", "Klimaanlagen"],
    description: "Wartung, Instandhaltung und Reparatur von Kälte- und Klimaanlagen. Regionaler Einsatz, keine langen Reisen.",
    intro: "Als Kältetechniker im Raum Koblenz warten und reparieren Sie Kälte- und Klimaanlagen im regionalen Einsatzgebiet – lange Reisen und Übernachtungen entfallen. Die Tätigkeit deckt das gesamte HKLS-Spektrum ab.",
    aufgaben: [
      "Wartung, Instandhaltung und Reparatur von Kälte- und Klimaanlagen",
      "Dichtheitskontrollen an Kälteanlagen gemäß ChemKlimaschutzV",
      "Fachgerechter Umgang mit Kältemitteln inklusive Rückgewinnung und Befüllung",
      "Störungsdiagnose an Kältekreisläufen, Regelungs- und Elektrotechnik",
      "Inbetriebnahme neuer Anlagen und Einweisung der Betreiber",
      "Dokumentation der Einsätze und Pflege der Anlagenhistorie",
    ],
    profil: [
      "Abgeschlossene Ausbildung als Mechatroniker für Kältetechnik oder vergleichbar",
      "Sachkunde nach ChemKlimaschutzV (Kategorie I oder II) von Vorteil",
      "Führerschein Klasse B für den regionalen Einsatz",
      "Gute Deutschkenntnisse",
      "Selbstständige, kundenorientierte Arbeitsweise",
    ],
    posted: "vor 3 Tagen",
    benefits: ["Kein Übernachten", "Firmenwagen", "30 Tage Urlaub", "Betriebliche Altersvorsorge"],
  },
  {
    id: "16",
    title: "Servicetechniker Photovoltaik (m/w/d)",
    category: "elektro",
    city: "Düsseldorf",
    region: "Nordrhein-Westfalen",
    lat: 51.227,
    lng: 6.773,
    salary: "44.000 – 54.000 €/Jahr",
    type: "Festanstellung",
    datePosted: "2026-06-26",
    tags: ["Photovoltaik", "Solartechnik", "Außendienst"],
    description: "Inbetriebnahme, Wartung und Instandsetzung von PV-Anlagen. Technische Analyse und Fehlerdiagnose an Solaranlagen.",
    intro: "Für den Ausbau der Solartechnik im Raum Düsseldorf suchen wir einen Servicetechniker Photovoltaik. Sie nehmen PV-Anlagen in Betrieb, warten sie und analysieren Fehler – ein Firmenwagen mit Privatnutzung gehört zur Ausstattung.",
    aufgaben: [
      "Inbetriebnahme von Photovoltaikanlagen inklusive Wechselrichter und Anlagenüberwachung",
      "Wartung und Instandsetzung von PV-Anlagen im Bestand",
      "Messungen und Prüfungen nach DIN EN 62446 (VDE 0126-23), u. a. Isolations- und Kennlinienmessung",
      "Technische Analyse und Fehlerdiagnose an Strings, Wechselrichtern und Unterkonstruktion",
      "Austausch defekter Module und Komponenten",
      "Dokumentation der Prüfergebnisse und Serviceeinsätze",
    ],
    profil: [
      "Abgeschlossene Ausbildung als Elektroniker für Energie- und Gebäudetechnik oder vergleichbar",
      "Erfahrung mit Photovoltaik- oder Wechselrichtertechnik von Vorteil",
      "Höhentauglichkeit für Arbeiten auf Dächern",
      "Führerschein Klasse B",
      "Gute Deutschkenntnisse und selbstständige Arbeitsweise",
    ],
    posted: "vor 6 Tagen",
    benefits: ["Firmenwagen (auch privat)", "Weiterbildungsbudget", "30 Tage Urlaub", "Betriebliche Altersvorsorge"],
  },
  {
    id: "17",
    title: "Elektroniker Anlagentechnik (m/w/d)",
    category: "elektro",
    city: "Dortmund",
    region: "Nordrhein-Westfalen",
    lat: 51.514,
    lng: 7.468,
    salary: "44.000 – 52.000 €/Jahr",
    type: "Festanstellung",
    datePosted: "2026-06-26",
    tags: ["Anlagentechnik", "Elektrotechnik", "Montage"],
    description: "Montage und Inbetriebnahme elektrischer Anlagen. Wartung und Fehlersuche in der Betriebselektrik.",
    intro: "In Dortmund montieren Sie elektrische Anlagen und nehmen sie in Betrieb – ergänzt um Wartung und Fehlersuche in der Betriebselektrik. Eine solide Position für Elektroniker, die Montage und Instandhaltung kombinieren möchten.",
    aufgaben: [
      "Montage elektrischer Anlagen und Anlagenkomponenten",
      "Inbetriebnahme und Funktionsprüfung neuer Installationen",
      "Wartung und Instandhaltung der Betriebselektrik",
      "Systematische Fehlersuche und Störungsbeseitigung",
      "Prüfungen ortsfester Anlagen nach DGUV Vorschrift 3",
      "Pflege der Anlagendokumentation und Schaltpläne",
    ],
    profil: [
      "Abgeschlossene Ausbildung in einem elektrotechnischen Beruf",
      "Erfahrung in der Anlagenmontage oder Betriebselektrik von Vorteil",
      "Sicherer Umgang mit Mess- und Prüfgeräten",
      "Gute Deutschkenntnisse",
      "Zuverlässige und genaue Arbeitsweise",
    ],
    posted: "vor 1 Woche",
    benefits: ["30 Tage Urlaub", "Betriebliche Altersvorsorge", "Jobticket", "Mitarbeiterevents"],
  },
  {
    id: "18",
    title: "Servicetechniker Anlagentechnik (m/w/d)",
    category: "mechatronik",
    city: "Hannover",
    region: "Niedersachsen",
    lat: 52.376,
    lng: 9.732,
    salary: "46.000 – 56.000 €/Jahr",
    type: "Festanstellung",
    datePosted: "2026-06-26",
    tags: ["Anlagentechnik", "Service", "Wartung"],
    description: "Service und Wartung von technischen Anlagen bei Industriekunden. Eigenverantwortliche Einsatzplanung, Dienstwagen.",
    intro: "Von Hannover aus betreuen Sie als Servicetechniker technische Anlagen bei Industriekunden in der Region. Ihre Einsätze planen Sie eigenverantwortlich – ein Dienstwagen, auch zur privaten Nutzung, steht Ihnen dafür zur Verfügung.",
    aufgaben: [
      "Service und Wartung technischer Anlagen bei Industriekunden",
      "Eigenverantwortliche Planung und Koordination der Serviceeinsätze",
      "Inspektion, Fehlerdiagnose und Instandsetzung vor Ort",
      "Austausch von Ersatz- und Verschleißteilen",
      "Abstimmung mit Kunden zu Terminen und durchgeführten Arbeiten",
      "Erstellung von Einsatz- und Wartungsberichten",
    ],
    profil: [
      "Abgeschlossene technische Ausbildung, z. B. als Mechatroniker oder Industriemechaniker mit Elektrokenntnissen",
      "Erfahrung im Service oder in der Anlagentechnik von Vorteil",
      "Führerschein Klasse B",
      "Gute Deutschkenntnisse und verbindliches Auftreten",
      "Hohes Maß an Selbstorganisation",
    ],
    posted: "vor 4 Tagen",
    benefits: ["Firmenwagen (auch privat)", "Spesen & Auslöse", "30 Tage Urlaub", "Betriebliche Altersvorsorge"],
  },
  {
    id: "19",
    title: "Anlagenmechaniker SHK (m/w/d)",
    category: "bau",
    city: "Frankfurt am Main",
    region: "Hessen",
    lat: 50.111,
    lng: 8.682,
    salary: "40.000 – 50.000 €/Jahr",
    type: "Festanstellung",
    datePosted: "2026-06-26",
    tags: ["SHK", "Sanitär", "Heizung"],
    description: "Installation und Wartung von Heizungs-, Sanitär- und Klimaanlagen. Kundendienst und Entstörung im Raum Frankfurt.",
    intro: "Als Anlagenmechaniker SHK im Raum Frankfurt installieren und warten Sie Heizungs-, Sanitär- und Klimaanlagen. Neben Neuinstallationen gehören Kundendienst- und Entstörungseinsätze im Stadtgebiet und Umland zu Ihrem Alltag.",
    aufgaben: [
      "Installation von Heizungs-, Sanitär- und Klimaanlagen in Neubau und Bestand",
      "Wartung und Instandhaltung von Heizsystemen, u. a. Brennwertgeräten und Wärmepumpen",
      "Kundendienst- und Entstörungseinsätze im Raum Frankfurt",
      "Montage von Rohrleitungssystemen und Sanitärobjekten",
      "Durchführung von Druck- und Dichtheitsprüfungen",
      "Dokumentation der Wartungs- und Serviceeinsätze",
    ],
    profil: [
      "Abgeschlossene Ausbildung als Anlagenmechaniker SHK oder vergleichbar",
      "Erfahrung im Kundendienst von Vorteil",
      "Führerschein Klasse B",
      "Gute Deutschkenntnisse für den Kundenkontakt",
      "Freundliches Auftreten und saubere Arbeitsweise",
    ],
    posted: "vor 2 Wochen",
    benefits: ["30 Tage Urlaub", "Firmenwagen", "Weiterbildungsbudget", "Betriebliche Altersvorsorge"],
  },
  {
    id: "20",
    title: "Mechatroniker für Kältetechnik (m/w/d)",
    category: "mechatronik",
    city: "Berlin",
    region: "Berlin",
    lat: 52.520,
    lng: 13.405,
    salary: "48.000 – 58.000 €/Jahr",
    type: "Festanstellung",
    datePosted: "2026-06-26",
    tags: ["Kältetechnik", "Mechatronik", "Berlin"],
    description: "Instandhaltung und Reparatur von Kälteanlagen. Wartung von Gewerbe- und Industriekälteanlagen im Raum Berlin.",
    intro: "In Berlin halten Sie als Mechatroniker für Kältetechnik Gewerbe- und Industriekälteanlagen instand – vom Kühlraum im Handel bis zur Prozesskälte in der Industrie. Die Einsätze konzentrieren sich auf das Berliner Stadtgebiet.",
    aufgaben: [
      "Instandhaltung und Reparatur von Gewerbe- und Industriekälteanlagen",
      "Wartung von Kälte- und Klimatechnik nach Herstellervorgaben",
      "Dichtheitsprüfungen und Kältemittel-Dokumentation gemäß ChemKlimaschutzV",
      "Fehlerdiagnose an Verdichtern, Verflüssigern und Regelungstechnik",
      "Umbauten und Modernisierungen bestehender Anlagen",
      "Pflege der Service- und Anlagendokumentation",
    ],
    profil: [
      "Abgeschlossene Ausbildung als Mechatroniker für Kältetechnik",
      "Erfahrung mit Gewerbe- oder Industriekälte von Vorteil",
      "Sachkunde nach ChemKlimaschutzV wünschenswert",
      "Führerschein Klasse B von Vorteil",
      "Gute Deutschkenntnisse und zuverlässige Arbeitsweise",
    ],
    posted: "vor 3 Tagen",
    benefits: ["30 Tage Urlaub", "Betriebliche Altersvorsorge", "Jobticket", "Weiterbildungsbudget"],
  },
  {
    id: "21",
    title: "Mechatroniker als Servicetechniker (m/w/d)",
    category: "mechatronik",
    city: "Köln",
    region: "Nordrhein-Westfalen",
    lat: 50.938,
    lng: 6.960,
    salary: "46.000 – 56.000 €/Jahr",
    type: "Festanstellung",
    datePosted: "2026-06-26",
    tags: ["Service", "Mechatronik", "Außendienst"],
    description: "Eigenständige Wartung und Instandhaltung mechatronischer Systeme bei Kunden im Raum Köln.",
    intro: "Für Kundeneinsätze im Raum Köln suchen wir einen Mechatroniker im Service. Sie arbeiten eigenständig an mechatronischen Systemen unterschiedlicher Kunden – mit einem Firmenwagen, den Sie auch privat nutzen können.",
    aufgaben: [
      "Eigenständige Wartung mechatronischer Systeme bei Kunden im Raum Köln",
      "Instandhaltung und Reparatur an Mechanik, Elektrik und Steuerungstechnik",
      "Eingrenzung von Fehlerursachen über die Gewerke hinweg",
      "Durchführung von Sicht- und Funktionsprüfungen",
      "Abstimmung der Einsätze mit Disposition und Kunden",
      "Dokumentation der durchgeführten Arbeiten",
    ],
    profil: [
      "Abgeschlossene Ausbildung als Mechatroniker oder vergleichbare Qualifikation",
      "Berufserfahrung im Außendienst oder Service von Vorteil",
      "Führerschein Klasse B",
      "Gute Deutschkenntnisse",
      "Selbstständige, verantwortungsbewusste Arbeitsweise",
    ],
    posted: "vor 5 Tagen",
    benefits: ["Firmenwagen (auch privat)", "30 Tage Urlaub", "Betriebliche Altersvorsorge", "Spesen & Auslöse"],
  },
  {
    id: "22",
    title: "Elektroniker Energie- und Gebäudetechnik (m/w/d)",
    category: "elektro",
    city: "Düren",
    region: "Nordrhein-Westfalen",
    lat: 50.804,
    lng: 6.491,
    salary: "44.000 – 54.000 €/Jahr",
    type: "Festanstellung",
    datePosted: "2026-06-26",
    tags: ["Gebäudetechnik", "EIB/KNX", "Smart Home"],
    description: "Planung und Installation von Gebäudeautomationssystemen, KNX-Technik und Energieverteilung im Raum Düren.",
    intro: "Im Raum Düren planen und installieren Sie moderne Gebäudetechnik – von der Energieverteilung bis zu KNX/EIB-Automation und Smart-Home-Lösungen. Planungsarbeiten können teilweise im Homeoffice erledigt werden.",
    aufgaben: [
      "Planung und Installation von Gebäudeautomationssystemen auf KNX/EIB-Basis",
      "Parametrierung und Inbetriebnahme von KNX-Komponenten mit der ETS",
      "Installation von Energieverteilungen und Zählerplätzen",
      "Umsetzung von Smart-Home-Funktionen wie Beleuchtungs-, Beschattungs- und Heizungssteuerung",
      "Prüfung und Messung nach DIN VDE 0100-600",
      "Einweisung der Nutzer und Erstellung der Übergabedokumentation",
    ],
    profil: [
      "Abgeschlossene Ausbildung als Elektroniker für Energie- und Gebäudetechnik",
      "Erfahrung mit KNX/EIB und der ETS-Software von Vorteil",
      "Führerschein Klasse B wünschenswert",
      "Gute Deutschkenntnisse für Planung und Kundenkontakt",
      "Strukturierte, eigenverantwortliche Arbeitsweise",
    ],
    posted: "vor 1 Woche",
    benefits: ["Homeoffice möglich", "30 Tage Urlaub", "Weiterbildungsbudget", "Betriebliche Altersvorsorge"],
  },
  {
    id: "23",
    title: "Elektroniker als Servicetechniker (m/w/d) – Deutschlandweit",
    category: "elektro",
    city: "Deutschlandweit",
    region: "Bundesweit",
    lat: 51.165,
    lng: 10.451,
    salary: "48.000 – 60.000 €/Jahr",
    type: "Festanstellung",
    datePosted: "2026-06-26",
    tags: ["Außendienst", "Dienstwagen", "Bundesweit"],
    description: "Service und Wartung elektrischer Anlagen bei Industriekunden bundesweit. Dienstwagen zur privaten Nutzung inklusive.",
    intro: "Diese Position als Servicetechniker Elektrotechnik führt Sie zu Industriekunden in ganz Deutschland. Sie sind mit dem Dienstwagen unterwegs, den Sie auch privat nutzen können – Reisebereitschaft ist hier Teil des Berufsbilds.",
    aufgaben: [
      "Service und Wartung elektrischer Anlagen bei Industriekunden bundesweit",
      "Fehlerdiagnose und Instandsetzung direkt vor Ort beim Kunden",
      "Durchführung wiederkehrender Prüfungen nach DGUV Vorschrift 3",
      "Inbetriebnahme und Modernisierung elektrotechnischer Komponenten",
      "Selbstständige Routen- und Einsatzplanung",
      "Erstellung von Prüfprotokollen und Serviceberichten",
    ],
    profil: [
      "Abgeschlossene Ausbildung in einem Elektroberuf",
      "Bundesweite Reisebereitschaft inklusive Übernachtungen",
      "Führerschein Klasse B",
      "Erfahrung im Industrieservice von Vorteil",
      "Gute Deutschkenntnisse und sicheres Auftreten beim Kunden",
    ],
    posted: "vor 2 Tagen",
    benefits: ["Firmenwagen (auch privat)", "Spesen & Auslöse", "30 Tage Urlaub", "Betriebliche Altersvorsorge"],
  },
  {
    id: "24",
    title: "Betriebselektroniker (m/w/d)",
    category: "elektro",
    city: "Stuttgart",
    region: "Baden-Württemberg",
    lat: 48.783,
    lng: 9.182,
    salary: "46.000 – 54.000 €/Jahr",
    type: "Festanstellung",
    datePosted: "2026-06-26",
    tags: ["Instandhaltung", "Elektronik", "Automobil"],
    description: "Elektrische Instandhaltung von Produktionsanlagen in der Automobilindustrie. Moderne Arbeitsumgebung, attraktive Sozialleistungen.",
    intro: "Am Standort Stuttgart halten Sie als Betriebselektroniker Produktionsanlagen der Automobilindustrie elektrisch instand. Sie arbeiten an hochautomatisierter Fertigungstechnik in einer modernen Arbeitsumgebung.",
    aufgaben: [
      "Elektrische Instandhaltung von Produktionsanlagen in der Automobilfertigung",
      "Störungsanalyse an verketteten, hochautomatisierten Fertigungslinien",
      "Fehlersuche an Robotik, Fördertechnik und SPS-Steuerungen",
      "Geplante Wartungen in produktionsfreien Zeiten",
      "Zusammenarbeit mit Anlagenherstellern und der Fertigungssteuerung",
      "Dokumentation der Maßnahmen im Instandhaltungssystem",
    ],
    profil: [
      "Abgeschlossene Ausbildung als Elektroniker für Betriebstechnik oder Automatisierungstechnik",
      "Erfahrung in der Instandhaltung automatisierter Fertigungsanlagen von Vorteil",
      "Grundkenntnisse in SPS-Technik wünschenswert",
      "Gute Deutschkenntnisse",
      "Teamfähigkeit und zuverlässige Arbeitsweise",
    ],
    posted: "vor 4 Tagen",
    benefits: ["30 Tage Urlaub", "Betriebliche Altersvorsorge", "Kantine", "Mitarbeiterrabatte"],
  },
  {
    id: "25",
    title: "Kältetechniker mit regionalem Einsatz (m/w/d)",
    category: "mechatronik",
    city: "Hamburg",
    region: "Hamburg",
    lat: 53.551,
    lng: 10.000,
    salary: "48.000 – 58.000 €/Jahr",
    type: "Festanstellung",
    datePosted: "2026-06-26",
    tags: ["Kältetechnik", "Regional", "Klimaanlagen"],
    description: "Wartung und Reparatur von Kälte- und Klimaanlagen im regionalen Einsatz. Keine Übernachtungen, täglich nach Hause.",
    intro: "Als Kältetechniker mit regionalem Einsatzgebiet rund um Hamburg sind Sie abends wieder zu Hause – Übernachtungen sind nicht vorgesehen. Sie betreuen Kälte- und Klimaanlagen im Großraum, unterwegs mit dem Firmenwagen, der auch privat genutzt werden kann.",
    aufgaben: [
      "Wartung und Reparatur von Kälte- und Klimaanlagen im Großraum Hamburg",
      "Regelmäßige Dichtheitskontrollen gemäß ChemKlimaschutzV",
      "Kältemittel-Handling nach den Vorgaben der F-Gase-Verordnung",
      "Störungsbehebung an Kälteaggregaten, Splitgeräten und Klimasystemen",
      "Beratung der Kunden zu Wartung und Energieeffizienz der Anlagen",
      "Dokumentation der Einsätze im Servicesystem",
    ],
    profil: [
      "Abgeschlossene Ausbildung als Mechatroniker für Kältetechnik oder vergleichbar",
      "Erfahrung im Service von Kälte- und Klimaanlagen von Vorteil",
      "Sachkundebescheinigung nach ChemKlimaschutzV wünschenswert",
      "Führerschein Klasse B",
      "Gute Deutschkenntnisse und eigenständige Arbeitsweise",
    ],
    posted: "vor 6 Tagen",
    benefits: ["Kein Übernachten", "Firmenwagen (auch privat)", "30 Tage Urlaub", "Betriebliche Altersvorsorge"],
  },
];

export const CATEGORIES = [
  { id: "all", label: "Alle Bereiche" },
  { id: "elektro", label: "Elektrotechnik" },
  { id: "mechatronik", label: "Mechatronik" },
  { id: "it", label: "IT / Automation" },
  { id: "bau", label: "Bau / TGA" },
] as const;

export const CATEGORY_COLORS: Record<string, string> = {
  elektro: "#f59e0b",
  mechatronik: "#3d7cc9",
  it: "#7c3aed",
  bau: "#22c55e",
};

export const CATEGORY_LABELS: Record<string, string> = {
  elektro: "Elektrotechnik",
  mechatronik: "Mechatronik",
  it: "IT / Automation",
  bau: "Bau / TGA",
};

// Haversine distance in km between two lat/lng points
export function distanceKm(lat1: number, lng1: number, lat2: number, lng2: number): number {
  const R = 6371;
  const dLat = ((lat2 - lat1) * Math.PI) / 180;
  const dLng = ((lng2 - lng1) * Math.PI) / 180;
  const a =
    Math.sin(dLat / 2) ** 2 +
    Math.cos((lat1 * Math.PI) / 180) *
      Math.cos((lat2 * Math.PI) / 180) *
      Math.sin(dLng / 2) ** 2;
  return R * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
}
