export type Job = {
  id: string;
  title: string;
  category: "elektro" | "mechatronik" | "it" | "bau";
  city: string;
  region: string;
  lat: number;
  lng: number;
  salary: string;
  type: string;
  tags: string[];
  description: string;
  posted: string;
};

export const JOBS: Job[] = [
  {
    id: "1",
    title: "Elektroniker für Betriebstechnik (m/w/d)",
    category: "elektro",
    city: "Frankenthal",
    region: "Rheinland-Pfalz",
    lat: 49.537,
    lng: 8.353,
    salary: "45.000 – 50.000 €/Jahr",
    type: "Festanstellung",
    tags: ["Schaltschrankbau", "Instandhaltung", "Gleitzeit"],
    description: "Verdrahtung von Schaltschränken, Montage und elektrische Installation von Maschinen und Anlagen. Keine Schichtarbeit, saubere Produktionsumgebung.",
    posted: "vor 2 Tagen",
  },
  {
    id: "2",
    title: "Servicetechniker Kältetechnik (m/w/d)",
    category: "mechatronik",
    city: "München",
    region: "Bayern",
    lat: 48.137,
    lng: 11.576,
    salary: "50.000 – 65.000 €/Jahr",
    type: "Festanstellung",
    tags: ["Kältetechnik", "Tiefkühlung", "Wartung"],
    description: "Wartung, Instandhaltung und Reparatur von Tiefkälteanlagen (bis –80 °C). Fehlerdiagnose und Austausch defekter Komponenten im Kundendienst.",
    posted: "vor 3 Tagen",
  },
  {
    id: "3",
    title: "Servicetechniker Elektrotechnik (m/w/d)",
    category: "elektro",
    city: "Leipzig",
    region: "Sachsen",
    lat: 51.340,
    lng: 12.375,
    salary: "46.000 – 52.000 €/Jahr",
    type: "Festanstellung",
    tags: ["Wartung", "Instandhaltung", "Außendienst"],
    description: "Wartung, Prüfung und Instandhaltung elektrischer Systeme und Anlagen beim Kunden vor Ort. Mo–Fr, keine Wochenendarbeit.",
    posted: "vor 1 Woche",
  },
  {
    id: "4",
    title: "Elektromonteur (m/w/d)",
    category: "elektro",
    city: "Offenbach",
    region: "Hessen",
    lat: 50.099,
    lng: 8.762,
    salary: "42.000 – 46.000 €/Jahr",
    type: "Festanstellung",
    tags: ["Montage", "Elektroinstallation", "Inbetriebnahme"],
    description: "Installation und Montage von elektrotechnischen Anlagen beim Kunden vor Ort. Verkabelung, Anschlussarbeiten und Inbetriebnahme.",
    posted: "vor 4 Tagen",
  },
  {
    id: "5",
    title: "Elektroniker Instandhaltung (m/w/d)",
    category: "elektro",
    city: "Mosbach",
    region: "Baden-Württemberg",
    lat: 49.353,
    lng: 9.149,
    salary: "46.000 – 50.000 €/Jahr",
    type: "Festanstellung",
    tags: ["Instandhaltung", "Produktion", "Keine Schicht"],
    description: "Instandhaltung und Reparatur elektrischer Anlagen in einem Produktionsunternehmen. Feste Arbeitszeiten, keine Schichtarbeit.",
    posted: "vor 5 Tagen",
  },
  {
    id: "6",
    title: "Betriebselektriker (m/w/d)",
    category: "elektro",
    city: "Münster",
    region: "Nordrhein-Westfalen",
    lat: 51.960,
    lng: 7.626,
    salary: "42.000 – 50.000 €/Jahr",
    type: "Festanstellung",
    tags: ["Betriebstechnik", "Wartung", "Produktion"],
    description: "Sicherstellung der elektrischen Betriebsbereitschaft von Maschinen und Anlagen. Störungsbeseitigung und vorbeugende Wartung.",
    posted: "vor 6 Tagen",
  },
  {
    id: "7",
    title: "SPS-Programmierer / Automatisierungstechniker (m/w/d)",
    category: "it",
    city: "Langenfeld",
    region: "Nordrhein-Westfalen",
    lat: 51.107,
    lng: 6.949,
    salary: "50.000 – 65.000 €/Jahr",
    type: "Festanstellung",
    tags: ["Siemens TIA Portal", "SPS", "Automatisierung"],
    description: "Entwicklung und Optimierung von SPS-Programmen für Produktionsanlagen. Inbetriebnahme und Optimierung von Automatisierungslösungen.",
    posted: "vor 3 Tagen",
  },
  {
    id: "8",
    title: "Betriebselektroniker (m/w/d)",
    category: "elektro",
    city: "Bad Oeynhausen",
    region: "Nordrhein-Westfalen",
    lat: 52.198,
    lng: 8.800,
    salary: "44.000 – 52.000 €/Jahr",
    type: "Festanstellung",
    tags: ["Elektronik", "Instandhaltung", "Produktion"],
    description: "Wartung und Instandhaltung elektronischer Betriebsmittel. Fehlerdiagnose und Reparatur an Produktionsanlagen.",
    posted: "vor 1 Woche",
  },
  {
    id: "9",
    title: "Betriebselektroniker (m/w/d)",
    category: "elektro",
    city: "Kerpen",
    region: "Nordrhein-Westfalen",
    lat: 50.869,
    lng: 6.695,
    salary: "42.000 – 52.000 €/Jahr",
    type: "Festanstellung",
    tags: ["Elektronik", "Betriebstechnik", "NRW"],
    description: "Instandhaltung und Reparatur elektronischer Anlagen in einem wachsenden Produktionsunternehmen. Abwechslungsreiche Aufgaben.",
    posted: "vor 2 Wochen",
  },
  {
    id: "10",
    title: "Mechatroniker (m/w/d)",
    category: "mechatronik",
    city: "Freiburg",
    region: "Baden-Württemberg",
    lat: 47.997,
    lng: 7.842,
    salary: "45.000 – 55.000 €/Jahr",
    type: "Festanstellung",
    tags: ["Mechatronik", "Montage", "Inbetriebnahme"],
    description: "Montage, Inbetriebnahme und Wartung mechatronischer Systeme. Abwechslungsreiche Tätigkeit in einem modernen Unternehmen.",
    posted: "vor 3 Tagen",
  },
  {
    id: "11",
    title: "Elektroniker für Betriebstechnik – Vollkonti (m/w/d)",
    category: "elektro",
    city: "Erding",
    region: "Bayern",
    lat: 48.306,
    lng: 11.907,
    salary: "50.000 – 60.000 €/Jahr",
    type: "Festanstellung",
    tags: ["Vollkontinuierlich", "Schichtarbeit", "Produktion"],
    description: "Instandhaltung elektrischer Anlagen im Vollkontinuierlichen Schichtbetrieb. Attraktive Schichtzulagen, 30 Urlaubstage.",
    posted: "vor 5 Tagen",
  },
  {
    id: "12",
    title: "Elektroniker für Betriebstechnik – 3-Schicht (m/w/d)",
    category: "elektro",
    city: "Heilbronn",
    region: "Baden-Württemberg",
    lat: 49.142,
    lng: 9.220,
    salary: "46.000 – 54.000 €/Jahr",
    type: "Festanstellung",
    tags: ["3-Schicht", "Instandhaltung", "Automatisierung"],
    description: "Elektrische Instandhaltung von Maschinen und Anlagen im 3-Schicht-Betrieb. Keine Wochenendarbeit, attraktive Schichtzulage.",
    posted: "vor 1 Woche",
  },
  {
    id: "13",
    title: "Elektroniker MSR-Technik / Gebäudeautomation (m/w/d)",
    category: "bau",
    city: "Köln",
    region: "Nordrhein-Westfalen",
    lat: 50.938,
    lng: 6.960,
    salary: "48.000 – 58.000 €/Jahr",
    type: "Festanstellung",
    tags: ["MSR-Technik", "Gebäudeautomation", "HLK"],
    description: "Planung, Installation und Inbetriebnahme von MSR-Technik in HLK-Anlagen. Service und Wartung von Gebäudeautomationssystemen.",
    posted: "vor 4 Tagen",
  },
  {
    id: "14",
    title: "Mechatroniker als Servicetechniker (m/w/d)",
    category: "mechatronik",
    city: "Bremen",
    region: "Bremen",
    lat: 53.079,
    lng: 8.801,
    salary: "44.000 – 54.000 €/Jahr",
    type: "Festanstellung",
    tags: ["Service", "Außendienst", "Mechatronik"],
    description: "Wartung und Instandhaltung mechatronischer Anlagen beim Kunden. Serviceorientierter Einsatz im Raum Bremen.",
    posted: "vor 2 Tagen",
  },
  {
    id: "15",
    title: "Kältetechniker (m/w/d)",
    category: "mechatronik",
    city: "Koblenz",
    region: "Rheinland-Pfalz",
    lat: 50.359,
    lng: 7.590,
    salary: "46.000 – 56.000 €/Jahr",
    type: "Festanstellung",
    tags: ["Kältetechnik", "HKLS", "Klimaanlagen"],
    description: "Wartung, Instandhaltung und Reparatur von Kälte- und Klimaanlagen. Regionaler Einsatz, keine langen Reisen.",
    posted: "vor 3 Tagen",
  },
  {
    id: "16",
    title: "Servicetechniker Photovoltaik (m/w/d)",
    category: "elektro",
    city: "Düsseldorf",
    region: "Nordrhein-Westfalen",
    lat: 51.227,
    lng: 6.773,
    salary: "44.000 – 54.000 €/Jahr",
    type: "Festanstellung",
    tags: ["Photovoltaik", "Solartechnik", "Außendienst"],
    description: "Inbetriebnahme, Wartung und Instandsetzung von PV-Anlagen. Technische Analyse und Fehlerdiagnose an Solaranlagen.",
    posted: "vor 6 Tagen",
  },
  {
    id: "17",
    title: "Elektroniker Anlagentechnik (m/w/d)",
    category: "elektro",
    city: "Dortmund",
    region: "Nordrhein-Westfalen",
    lat: 51.514,
    lng: 7.468,
    salary: "44.000 – 52.000 €/Jahr",
    type: "Festanstellung",
    tags: ["Anlagentechnik", "Elektrotechnik", "Montage"],
    description: "Montage und Inbetriebnahme elektrischer Anlagen. Wartung und Fehlersuche in der Betriebselektrik.",
    posted: "vor 1 Woche",
  },
  {
    id: "18",
    title: "Servicetechniker Anlagentechnik (m/w/d)",
    category: "mechatronik",
    city: "Hannover",
    region: "Niedersachsen",
    lat: 52.376,
    lng: 9.732,
    salary: "46.000 – 56.000 €/Jahr",
    type: "Festanstellung",
    tags: ["Anlagentechnik", "Service", "Wartung"],
    description: "Service und Wartung von technischen Anlagen bei Industriekunden. Eigenverantwortliche Einsatzplanung, Dienstwagen.",
    posted: "vor 4 Tagen",
  },
  {
    id: "19",
    title: "Anlagenmechaniker SHK (m/w/d)",
    category: "bau",
    city: "Frankfurt am Main",
    region: "Hessen",
    lat: 50.111,
    lng: 8.682,
    salary: "40.000 – 50.000 €/Jahr",
    type: "Festanstellung",
    tags: ["SHK", "Sanitär", "Heizung"],
    description: "Installation und Wartung von Heizungs-, Sanitär- und Klimaanlagen. Kundendienst und Entstörung im Raum Frankfurt.",
    posted: "vor 2 Wochen",
  },
  {
    id: "20",
    title: "Mechatroniker für Kältetechnik (m/w/d)",
    category: "mechatronik",
    city: "Berlin",
    region: "Berlin",
    lat: 52.520,
    lng: 13.405,
    salary: "48.000 – 58.000 €/Jahr",
    type: "Festanstellung",
    tags: ["Kältetechnik", "Mechatronik", "Berlin"],
    description: "Instandhaltung und Reparatur von Kälteanlagen. Wartung von Gewerbe- und Industriekälteanlagen im Raum Berlin.",
    posted: "vor 3 Tagen",
  },
  {
    id: "21",
    title: "Mechatroniker als Servicetechniker (m/w/d)",
    category: "mechatronik",
    city: "Köln",
    region: "Nordrhein-Westfalen",
    lat: 50.938,
    lng: 6.960,
    salary: "46.000 – 56.000 €/Jahr",
    type: "Festanstellung",
    tags: ["Service", "Mechatronik", "Außendienst"],
    description: "Eigenständige Wartung und Instandhaltung mechatronischer Systeme bei Kunden im Raum Köln.",
    posted: "vor 5 Tagen",
  },
  {
    id: "22",
    title: "Elektroniker Energie- und Gebäudetechnik (m/w/d)",
    category: "bau",
    city: "Düren",
    region: "Nordrhein-Westfalen",
    lat: 50.804,
    lng: 6.491,
    salary: "44.000 – 54.000 €/Jahr",
    type: "Festanstellung",
    tags: ["Gebäudetechnik", "EIB/KNX", "Smart Home"],
    description: "Planung und Installation von Gebäudeautomationssystemen, KNX-Technik und Energieverteilung im Raum Düren.",
    posted: "vor 1 Woche",
  },
  {
    id: "23",
    title: "Elektroniker als Servicetechniker (m/w/d) – Deutschlandweit",
    category: "elektro",
    city: "Deutschlandweit",
    region: "Bundesweit",
    lat: 51.165,
    lng: 10.451,
    salary: "48.000 – 60.000 €/Jahr",
    type: "Festanstellung",
    tags: ["Außendienst", "Dienstwagen", "Bundesweit"],
    description: "Service und Wartung elektrischer Anlagen bei Industriekunden bundesweit. Dienstwagen zur privaten Nutzung inklusive.",
    posted: "vor 2 Tagen",
  },
  {
    id: "24",
    title: "Betriebselektroniker (m/w/d)",
    category: "elektro",
    city: "Stuttgart",
    region: "Baden-Württemberg",
    lat: 48.783,
    lng: 9.182,
    salary: "46.000 – 54.000 €/Jahr",
    type: "Festanstellung",
    tags: ["Instandhaltung", "Elektronik", "Automobil"],
    description: "Elektrische Instandhaltung von Produktionsanlagen in der Automobilindustrie. Moderne Arbeitsumgebung, attraktive Sozialleistungen.",
    posted: "vor 4 Tagen",
  },
  {
    id: "25",
    title: "Kältetechniker mit regionalem Einsatz (m/w/d)",
    category: "mechatronik",
    city: "Hamburg",
    region: "Hamburg",
    lat: 53.551,
    lng: 10.000,
    salary: "48.000 – 58.000 €/Jahr",
    type: "Festanstellung",
    tags: ["Kältetechnik", "Regional", "Klimaanlagen"],
    description: "Wartung und Reparatur von Kälte- und Klimaanlagen im regionalen Einsatz. Keine Übernachtungen, täglich nach Hause.",
    posted: "vor 6 Tagen",
  },
];

export const CATEGORIES = [
  { id: "all", label: "Alle Bereiche" },
  { id: "elektro", label: "Elektrotechnik" },
  { id: "mechatronik", label: "Mechatronik" },
  { id: "it", label: "IT / Automation" },
  { id: "bau", label: "Bau / TGA" },
] as const;

export const CATEGORY_COLORS: Record<string, string> = {
  elektro: "#f59e0b",
  mechatronik: "#3d7cc9",
  it: "#7c3aed",
  bau: "#22c55e",
};

export const CATEGORY_LABELS: Record<string, string> = {
  elektro: "Elektrotechnik",
  mechatronik: "Mechatronik",
  it: "IT / Automation",
  bau: "Bau / TGA",
};

// Haversine distance in km between two lat/lng points
export function distanceKm(lat1: number, lng1: number, lat2: number, lng2: number): number {
  const R = 6371;
  const dLat = ((lat2 - lat1) * Math.PI) / 180;
  const dLng = ((lng2 - lng1) * Math.PI) / 180;
  const a =
    Math.sin(dLat / 2) ** 2 +
    Math.cos((lat1 * Math.PI) / 180) *
      Math.cos((lat2 * Math.PI) / 180) *
      Math.sin(dLng / 2) ** 2;
  return R * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
}
